#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hidd_demos

EXTRA_COMPONENT_DIRS =  $(IDF_PATH)/components

COMPONENT_ADD_INCLUDEDIRS := components/include	\
								

include $(IDF_PATH)/make/project.mk
