[build]
target = "atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude promicro"
rustflags = [
  # ..
  "-C", "inline-threshold=275", # +
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mangled-names"]
