[build]
target = "atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude promicro"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mangled-names"]
